kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("menu.urls", namespace="menu")),
    path("accounts/", include("django.contrib.auth.urls")),
    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menu/urls.py
from django.urls import path

from menu.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookExperienceUpdateView,
    CookDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    toggle_assign_to_dish
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "categories/",
        CategoryListView.as_view(),
        name="category-list",
    ),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="category-create",
    ),
    path(
        "categories/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
]

app_name = "menu"

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.previous_page_number %}"
             class="page-link pagination">
            prev
          </a>
        </li>
      {% endif %}
      <li class="page-item">
        <span class="page-link dark">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}"
             class="page-link pagination">
            next
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/sidebar.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="{% url 'menu:index' %}">PRIME</a>

  <!-- Links -->
  <ul class="navbar-nav">
    {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{ user.get_absolute_url }}">
          {{ user.get_username }}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">
          Logout
        </a>
      </li>
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login'%}?next={{request.path}}">
          Login
        </a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'menu:cook-list' %}">
        Cooks
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'menu:dish-list' %}">
        Dishes
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'menu:category-list' %}">
        Categories
      </a>
    </li>
  </ul>
</nav>