kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("menu.urls", namespace="menu")),
    path("accounts/", include("django.contrib.auth.urls")),
    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

menu/urls.py
from django.urls import path

from menu.views import (
    index,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookExperienceUpdateView,
    CookDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    toggle_assign_to_dish
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "categories/",
        CategoryListView.as_view(),
        name="category-list",
    ),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="category-create",
    ),
    path(
        "categories/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list"
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail"
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
]

app_name = "menu"

menu/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("menu:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ["category"]

    def __str__(self):
        return f"{self.name} - {self.price}"

menu/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from menu.models import Dish, Cook


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self):
        return validate_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


class CookExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience"]

    def clean_years_of_experience(self):
        return validate_years_of_experience(
            self.cleaned_data["years_of_experience"]
        )


def validate_years_of_experience(
    years_of_experience,
):
    if years_of_experience < 1:
        raise ValidationError(
            "Experience should be greater than 1 year"
        )
    return years_of_experience


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class CategorySearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )

menu/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from menu.forms import (
    CookCreationForm,
    CookExperienceUpdateForm,
    CookSearchForm,
    DishSearchForm,
    DishForm,
    CategorySearchForm
)
from menu.models import Cook, Dish, Category


@login_required
def index(request):

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_categories = Category.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_categories": num_categories,
        "num_visits": num_visits + 1,
    }

    return render(request, "menu/index.html", context=context)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    name = Category
    context_object_name = "category_list"
    template_name = "menu/category_list.html"
    queryset = Category.objects.all()
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = CategorySearchForm(initial={
            "name": name
        })
        return context

    def get_queryset(self):
        form = CategorySearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        # return self.queryset


class CategoryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy("menu:category-list")


class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Category
    fields = "__all__"
    success_url = reverse_lazy("menu:category-list")


class CategoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Category
    success_url = reverse_lazy("menu:category-list")
        

class DishListView(LoginRequiredMixin, generic.ListView):
    name = Dish
    paginate_by = 5
    queryset = Dish.objects.all().select_related("category")
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("dish", "")
        context["search_form"] = DishSearchForm(initial={
            "name": name
        })
        return context

    def get_queryset(self):
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("menu:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("menu:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("menu:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    # queryset = Cook.objects.all()
    queryset = Cook.objects.prefetch_related("dishes__category")
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(initial={
            "username": username
        })
        return context

    def get_queryset(self):
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("dishes__cooks")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookExperienceUpdateForm
    success_url = reverse_lazy("menu:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("menu:cook-list")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    if (
        Dish.objects.get(id=pk) in cook.dishes.all()
    ):
        cook.dishes.remove(pk)
    else:
        cook.dishes.add(pk)
    return HttpResponseRedirect(
        reverse_lazy("menu:dish-detail", args=[pk])
    )

templates/menu/category_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} category </h1>
  <form action="" method="post" novalidate class="col-sm-6">
    {% csrf_token %}
    {{ form|crispy }}

    <div class="modal-footer">
      <a href="{% url 'menu:category-list' %}" class="btn btn-secondary link-to-page">
        Cancel
      </a>
      <input type="submit" value="Submit" class="btn btn-dark">
    </div>
  </form>
{% endblock %}

templates/menu/category_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="row">
    <div class="col-sm-6 pl-0">
      <form action="" method="get" class="form-inline">
        {{ search_form|crispy }}
        <input type="submit" value="Search" class="btn btn-secondary">
        <a href="{% url 'menu:category-create' %}"
           class="btn btn-secondary link-to-page">
          Add category
        </a>
      </form>
    </div>
  </div>
  <h1 class="py-2 text-center margin font-weight-bolder">
    Dish categories
  </h1>

  {% if category_list %}
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Category</th>
        <th>Update category</th>
        <th>Delete category</th>
      </tr>
      {% for category in category_list %}
        <tr>
          <td>
              {{ category.id }}
          </td>
          <td>
              {{ category.name }}
          </td>
          <td>
{#            <a class="text-body"#}
{#               href="{% url 'menu:category-update' pk=category.id %}">#}
{#              <i class="bi bi-pencil-square"></i>#}
{#            </a>#}
            <a class="btn btn-secondary" href="{% url 'menu:category-update' pk=category.id %}" role="button">
              <i class="bi bi-pencil-square"></i>
            </a>
          </td>
          <td>
                  <!-- Button trigger modal -->
            <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#deleteCategory">
              <i class="bi bi-trash-fill"></i>
            </button>

            <!-- Modal -->
            <div class="modal fade" id="deleteCategory" tabindex="-1" role="dialog" aria-labelledby="deleteCategoryLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="deleteCategoryLabel">Delete this category?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <form action="{% url 'menu:category-delete' pk=category.id %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-dark">Delete</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no categories.</p>
  {% endif %}
{% endblock %}

templates/menu/cook_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex flex-row-reverse">
    <div class="pl-0 pt-1">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#deleteCook">
        Delete
      </button>

      <!-- Modal -->
      <div class="modal fade" id="deleteCook" tabindex="-1" role="dialog" aria-labelledby="deleteCookLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteCookLabel">Delete this cook?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <form action="{% url 'menu:cook-delete' pk=cook.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-dark">Delete</button>
              </form>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="pl-0 pt-1">
      <a href="{% url 'menu:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
        Update experience
      </a>
    </div>
  </div>
  <h1 class="text-center font-weight-bolder">
    Username: {{ cook.username }}
  </h1>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h5 class="font-weight-bolder">
          <strong>First name:</strong>{{ cook.first_name }}
        </h5>
        <h5 class="font-weight-bolder">
          <strong>Last name:</strong> {{ cook.last_name }}
        </h5>
        <h5 class="font-weight-bolder">
          <strong>Years of experience:</strong> {{ cook.years_of_experience }}
        </h5>
        <h5 class="font-weight-bolder">
          <strong>Is staff:</strong> {{ cook.is_staff }}
        </h5>
        <h5 class="font-weight-bolder">
          <strong>Dishes:</strong>
        </h5>
          <ul>
            {% for dish in cook.dishes.all %}
              <li>
              <a>{{ dish.name }} (type: {{ dish.category.name }})</a>
              </li>
            {% empty %}
              <h5 class="font-weight-bolder">No dishes!</h5>
            {% endfor %}
          </ul>
      </div>
    </div>
  </div>

{% endblock %}

templates/menu/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create cook</h1>
  <form action="" method="post" novalidate class="col-sm-6">
    {% csrf_token %}
    {{ form|crispy }}

    <div class="modal-footer">
      <a href="{% url 'menu:cook-list' %}" class="btn btn-secondary link-to-page">
        Cancel
      </a>
      <input type="submit" value="Submit" class="btn btn-dark">
    </div>
  </form>
{% endblock %}

templates/menu/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="row">
    <div class="col-sm-6 pl-0">
     <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
      <input type="submit" value="Search" class="btn btn-secondary">
      <a href="{% url 'menu:cook-create' %}" class="btn btn-secondary link-to-page">
        Add cook
      </a>
     </form>
    </div>
  </div>
    <h1 class="py-2 text-center margin font-weight-bolder">
      Greet our cooks
    </h1>

    {% if cook_list %}
    <table class="table table-hover">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Year of experience</th>
      </tr>
    {% for cook in cook_list %}
      <tr>
        <td>{{ cook.id }}</td>
        <td>
          <a class="text-body" href="{{ cook.get_absolute_url }}">
            {{ cook.username }} {% if user == cook %} (Me){% endif %}
          </a>
        </td>
        <td>{{ cook.first_name }}</td>
        <td>{{ cook.last_name }}</td>
        <td>{{ cook.years_of_experience }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no cooks in the service.</p>
    {% endif %}
{% endblock %}

templates/menu/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex flex-row-reverse">
    <div class="pl-0 pt-1">
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#deleteDish">
        Delete
      </button>

      <!-- Modal -->
      <div class="modal fade" id="deleteDish" tabindex="-1" role="dialog" aria-labelledby="deleteDishLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteDishLabel">Delete this dish?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <form action="{% url 'menu:dish-delete' pk=dish.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-dark">Delete</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="pl-0 pt-1">
      <a href="{% url 'menu:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
        Update
      </a>
    </div>
    <div class="pl-0 pt-1">
      {% if dish in user.dishes.all %}
        <a href="{% url 'menu:toggle-dish-assign' pk=dish.id %}" class="btn btn-secondary link-to-page">
          Delete me from this dish
        </a>
      {% else %}
        <a href="{% url 'menu:toggle-dish-assign' pk=dish.id %}" class="btn btn-secondary link-to-page">
          Assign me to this dish
        </a>
      {% endif %}
    </div>
  </div>

  <h1 class="text-center font-weight-bolder">
    {{ dish.name }}
  </h1>
  <br>
    <h5 class="font-weight-bolder">
      Dish type: {{ dish.category.name }}
    </h5>
    <h5 class="font-weight-bolder">
      Dish price: {{ dish.price }}UAH
    </h5>
    <h5 class="font-weight-bolder">
      Dish description: {{ dish.description }}
    </h5>
    <h5 class="font-weight-bolder">Cooks:
      <ul>
        {% for cook in dish.cooks.all %}
          <li>{{ cook.username }} - {{ cook.first_name }} {{ cook.last_name }}</li>
        {% endfor %}
      </ul>
    </h5>
{% endblock %}

templates/menu/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} dish </h1>
  <form action="" method="post" novalidate class="col-sm-6">
    {% csrf_token %}
    {{ form|crispy }}

    <div class="modal-footer">
      <a href="{% url 'menu:dish-list' %}" class="btn btn-secondary link-to-page">
        Cancel
      </a>
      <input type="submit" value="Submit" class="btn btn-dark">
    </div>
  </form>
{% endblock %}

templates/menu/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <div class="row">
    <div class="col-sm-6 pl-0">
      <form action="" method="get" class="form-inline">
        {{ search_form|crispy }}
        <input type="submit" value="Search" class="btn btn-secondary">
        <a href="{% url 'menu:dish-create' %}" class="btn btn-secondary link-to-page">
        Add dish
        </a>
      </form>
    </div>
  </div>

  <h1 class="py-2 text-center font-weight-bolder margin">
    Our dishes
  </h1>

  {% if dish_list %}
    <ul class="py-2 text-center list-unstyled">
      {% for dish in dish_list %}
        <li class="font-weight-bolder">
          <a class="text-body" href="{% url "menu:dish-detail" pk=dish.id %} ">{{ dish.name }}</a>
          {{ dish.category.name }} - {{ dish.price }}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p class="font-weight-bolder">Sorry we are updating menu</p>
  {% endif %}
{% endblock %}

templates/menu/index.html
{% extends "base.html" %}

{% block content %}
  <h2 class="py-2 text-center margin font-weight-bolder">
    Welcome to PRIME Restaurant!
  </h2>
    <p class="py-2 text-center">The best restaurant ever!</p>
    <h3 class="py-2 text-center font-weight-bolder">
      The Restaurant service has the following record counts:
    </h3>
    <div class="d-flex">
      <ul class="list-inline mx-auto justify-content-center">
          <li class="list-inline-item">
            <strong>Dishes:</strong> {{ num_dishes }}
          </li>
          <li class="list-inline-item">
            <strong>Cooks:</strong> {{ num_cooks }}
          </li>
          <li class="list-inline-item">
            <strong>Categories:</strong> {{ num_categories }}
          </li>
      </ul>
    </div>

    <p class="py-2 text-center">You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>
{% endblock %}